- anaoptions.py
Addressing: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/18
In `anaoptions.py` have changed the default ztrim value from 0 to 4 to match with what is set as the default value when scans are taken in `vfatqc-python-scripts/qcoptions.py` at:
https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/4b03d64b08c1bc9b70ae2fcbd5f4ea624d289c6f/qcoptions.py#L13
Possible that the user tries to analyze data with the wrong ztrim due to ignorance. For example the user takes an scurve without supplying anything to the `--ztrim` argument in `vfatqc-python-scripts/ultraScurve.py`.  Here the data is recorded with `options.ztrim=4` by default.  The user then tries to analyze this data with `anaUltraScurve.py` and again does not supply a `--ztrim` argument.  Here the analysis is …
> Feature Request: Sync Default ztrim with vfatqc-python-scripts

- fitting/fitScanData.py
Addesses issue #15 by reading the number of events from the S-curve trees.
The S-curve fit function has the number of events hard-coded to 1000, but can be changed in `ultraScurve`. Detect it from the S-curve tree instead, to enable using data produced with non-default `--nevts`.
The implementation is not as suggested in #15, but will rather read the number of events from the tree. It's IMHO less error-prone: there is no need for an additional parameter to `fitScanData` (and flag to `anaUltraScurve.py`), that could be forgotten. The fit function will "just work" unless supplied with inconsistent trees (for sample merged using `hadd`), in which case an error may even be thrown (depending on the parameters used to generate the `hadd`ed trees).
See #15.
The changes were tested using data …
> Read the event count from the SCurve data tree

- anaUltraLatency.py
Addressing: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/30
TObjects produced by `anaUltraLatency.py` stored in the output file will now be placed in the correct `VFATN` TDirectories.
Output TFile was not organized, plots for VFATN were not stored in `VFATN` TDirectory.
Re-analyzed old data.
```
anaUltraLatency.py -i LatencyScanData.root -o LatTest.root
```
> Bug Fix: TDirectory usage in anaUltraLatency.py

- macros/plot_eff.py
- setup/paths.sh
The script `macros/plot_eff.py` will make an efficiency plot from data acquired with `vfatqc-python-scripts/ultraLatency.py`.
If someone has a controlled trigger source to take data only from a given spot on the detector you could use `vfatqc-python-scripts/ultraLatency.py` to measure the detector's efficiency
Sample data put in the input file:
```
more listOfScanDates.txt           
ChamberName	scandate	V_{mon}
GE11-VI-L-CERN-0001	2017.08.30.15.03	3551
GE11-VI-L-CERN-0001	2017.08.30.21.39	3663
GE11-VI-L-CERN-0001	2017.08.31.08.28	3714
```
Calling:
```
plot_eff.py listOfScanDates.txt --vfatList=12,13 --latSig=44 --print
```
Here:
- `--vfatList` is the list of VFATs your targeted trigger source covers (e.g. a 10x10 scintillating tile above VFATs 12 & 13).
- `--latSig` is the latency bin …
> New Feature: Making Eff Plots from Ultra Latency Scans

- .gitignore
- README.md
- anaInfo.py
- ana_scans.py
- anautilities.py
- macros/gemPlotter.py
- macros/gemPlotterAllChannels.sh
- mapping/chamberInfo.py
- requirements.txt
Starting to address: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/33
Right now if a particular plot of interest is desired a user has to make it by hand.  This feature seeks to address that.  The user provides a `tab` delimited text file `listOfScanDates.txt` of the form:
```
ChamberName scandate    <IndepVarName>
cName date    IndepVarVal1
cName date    IndepVarVal2
cName date    IndepVarVal3
...
...
cName date    IndepVarValN-1
cName date    IndepVarValN
```
And calls:
```
gemPlotter.py --anaType=trim --infilename=listOfScanDates.txt --vfatList=<comma separated list of integers> --strip=49 --branchName=<Name>
```
Then a plot of `branchName` vs `IndepVarName` from the scan dates specified, for each of the VFATs specified will be created.  Please note that `cName` need …
> Feature Implementation: Adding Generic Plotter by scandate

- README.md
- macros/gemPlotter.py
- macros/gemTreeDrawWrapper.py
The `gemPlotter.py` macro can now make arbitrary plots against alphanumeric independent variables.
Before if user wanted to plot against an alphanumeric independent variable (e.g. GEMINImXXLY, scandate, etc...) they had to convert it to a numeric value.  Now alphanumeric input is supported with the command line argument `--alphaLabels`.
I re-ran some old analysis to confirm existing functionality was preserved and added functionality worked.  See screenshots.
With alphanumeric labels:
```
gemPlotter.py -ilistOfScanDates_Trim.txt -s10 -v10 --anaType=trimAna --branchName=trimDAC --axisMin=0 --axisMax=31 --alphaLabels
```
```
gemPlotter.py -ilistOfScanDates_Trim.txt -v10 --anaType=trimAna --branchName=trimDAC --make2D --axisMin=-1 --axisMax=31 --alphaLabels
```
With only numeric labels:
``` …
```
> New Feature: gemPlotter.py now supports alphanumeric indep variables

- anaUltraScurve.py
Addressing https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/37
Now the `overlay_fit()` function in `anaUltraScurve.py` will take the event count as an input and use it for the fit.
If someone used the `-b` option the fit defined in `overlay_fit()` would not be correct for scurves taken with event counts different from the default.
I re-ran an old anaysis:
```
anaUltraScurve.py -i$DATA_PATH/GE11-VI-L-CERN-0001/scurve/current/SCurveData.root --ztrim=4 -b -f
```
> Bug Fix: Addressing #37

- README.md
- anaUltraLatency.py
- ana_scans.py
- macros/plot_eff.py
The fitting performed in `anaUltraLatency.py` leaves something to be desired.  In this PR the functionality is changed such that the latency distributions are not fit by default.  Instead three new options are added to `anaUltraLatency.py`:
- `-f`, `--fit` flag to perform fit,
- `--latSigRange` comma separated pair of integers specifying the range of the signal in an N vs. Latency distribution, and
- `--latSigMaskRange` comma separated pair of integers specifying the portion of an N vs. Latency distribution to not consider as noise
If an example signal range is given as  `--latSigRange=41,42` and  `--latSigMaskRange` is not specified the default behavior is then treated as latSigRange_Min-1 and latSigRange_Max+1, so [40,43] in this case.
These parameters will then be used to fit the …
> Better Fitting of Ultra Latency Scans

- anaInfo.py
- anaUltraLatency.py
- anautilities.py
The data that is plotted by `anaUltraLatency.py` is now also stored in an output `TTree` object.
Quality of life feature. This allows `gemPlotter.py` and `gemTreeDrawWrapper.py` to also plot this data in new ways.
I re-ran old analysis.  No changes to syntax.
> New Feature: anaUltraLatency now also makes an output TTree

- anaInfo.py
- anaUltraScurve.py
- anaUltraThreshold.py
- ana_scans.py
Bug fix of https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/45
Now anaUltraThreshold.py now also makes an output `TTree` object called `thrAnaTree` which stores the trimRange and VT1 determined for each VFAT.
Running `ana_scans.py` with `--series` option caused a crash.
Now with `anaUltraThreshold.py` stores the trimRange and vt1 values it computes in an output `TTree` object which can be used with `gemPlotter.py` or `gemTreeDrawWrapper.py`.
I re-ran an old analysis via `ana_scans.py` using the `--series` option.
> New Feature & Bug Fix: anaUltraThreshold.py now makes output TTree and BugFix #45

- anaUltraLatency.py
- anaUltraScurve.py
- anaUltraThreshold.py
Address: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/50
The ChipID1 register will now be stored in output TTree and config files as the `vfatID` branch.  Note if the input file does *not* have the `vfatID` branch the output TTree will have a `vfatID` branch with all leaves equal to 0 (same for the output config files).
As we move forward eventually we will be configuring with the information that will be stored in the database.  We should be able to cross-check that the info stored for a given VFAT in the database matches the VFAT that is being configured on the hardware.  The best way to do this is to compare the supplied `vfatID` with the `ChipID1` register on the VFAT since they should be identical.
Additionally in our calibration data there is no way to know which …
> New Feature: ChipID added to TTree's and Config Files

- anaInfo.py
- anaUltraThreshold.py
- ana_scans.py
- anautilities.py
Updates the analysis control to allow analysis of various different types of `VT1` scans
The `ultraThreshold` module can be configured to take:
* VT1 scan vs channel using tracking data
* VT1 scan vs VFAT using tracking data
* VT1 scan vs VFAT using trigger data (s-bits), which allows much faster scanning of the high threshold tails
* http://cmsonline.cern.ch/cms-elog/1026783
* New configurations are being generated using analysis of both per-channel and per VFAT w/ trigger data
> Adding threshold scan control to the analysis

- anaInfo.py
- anaUltraScurve.py
- anautilities.py
- fitting/fitScanData.py
Refactoring of `anaUltraScurve.py` with updates/additions to supporting tools.
All distributions created will now be in fC.  The output `TFile` will have relevant s-curve parameters stored in fC.  The default behavior is to use the `vfat2` `VCAL` to `fC` conversion that has been hard coded for some time.  The user can supply an external text file which specifies the conversion between the `CAL DAC` (either `vfat2` or `vfat3`) to `fC` using the `--calFile` argument.  The expected format of this file is shown as:
```
vfatN/I:slope/F:intercept/F
0   0.2692  -2.629748
1   0.238106    -2.65316
2   0.2532  -2.193826
3   0.276783    -2.477547
...
5   1.000000    0.000000    
...
...
```
If one prefers to stick in terms of `DAC` units simply supply a slope of `1.0` with an intercept of `0.0` as …
> Refactoring of anaUltraScurve.py and additional output distributions

- README.md
- anaUltraScurve.py
- anautilities.py
- macros/plotSCurveFitResults.py
- mapping/chamberInfo.py
New tool for visualizing results from multiple s-curve scandates.
I wanted to plot per VFAT distributions from multiple scurves on the same TCanvas, there was no "go to" tool for that yet.
I made a tool to do this, see example calling syntax in updated `README.md`.
Example outputs:
> New Tool For Visualizing Results from Multiple Scurve Runs

- anaUltraScurve.py
- anautilities.py
- fitting/fitScanData.py
- macros/plotSCurveFitResults.py
To assist in understanding https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/77 have added summary plots for the effective pedestal distribution.
Recall the effective pedestal of a channel is determined via:
```
s_curve_equation.Eval(0 fC)
``` 
So this is the number of times the channel's comparator fires when zero charge is injected by the calibration module.  Obviously a healthy channel has 0 hits.
Additionally there is a new utility function `parseCalFile(...)` that will parse an input text file which provides the slope and intercept values for the `VCAL` or `CFG_CAL_DAC` conversion to `fC`.
Finally `plotSCurveFitResults.py` will now also make comparison plots for scurve pedestals as well.
Multiple places needed DAC units to fC conversion so made a utility function for …
> New Features: Effective Pedestal Distributions 

- anaUltraScurve.py
The `gFitSummary_VFATX` plots where being made with a mis-matched x-axis due to an array indexing bug.
Before the `gFitSummary_VFATX` plots used an incorrect x-axis due to an array indexing issue.
Re-ran old analysis to confirm fix was made correctly.
Notice the channels with the very narrow s-curves are assigned the wrong strip number in the `gFitSummary_VFAT5` plot.
Notice in each case the 2D histogram uses the "correct" x-axis mapping (e.g. `strip` to `vfatCH`) but  `gFitSummary_VFAT5` plot is only correct in the second case.
> Bug Fix: Fit Summary Plot was using incorrectly mapped x-axis

- anautilities.py
- macros/gemPlotter.py
An typo in an import caused `gemPlotter.py` to crash.  Additionally if a 2 column file was specified as the `listOfScanDates.txt` file the independent variable name (e.g. `scandate`) was not properly stored.
`gemPlotter.py` crashed due to typo in import.
Output files were not properly labeled as `<dep. var>_vs_<indep. var>` in the case of a 2-column input file.
Re-ran old analysis:
```
gemPlotter.py -ilistOfScanDates_Trim.txt --anaType=trimAna --branchName=trimDAC --vfat=12 --make2D --alphaLabels
```
> Bug Fix: Fixed an import error in gemPlotter.py

- anaUltraScurve.py
- fitting/fitScanData.py
The `vfat3` team has decided to change the convention for the calibration coefficients `calDAC2Q_m` and `calDAC2Q_b`.  Previously in voltage step mode the "inverted" `CFG_CAL_DAC` register value was used, i.e.:
```
Q = calDAC2Q_m * (256 - CFG_CAL_DAC) + calDAC2Q_b
``` 
Now the raw register value will be used, e.g.:
```
Q = calDAC2Q_m * (CFG_CAL_DAC) + calDAC2Q_b
```
This was reported by Henri who is developing the `vfat3` production testing:
>My idea was to make the fit on the raw register value so the charge equation for the voltage mode would become:
>Q=m*CAL_DAC+b
>which in my mind would be more straight forward and avoid confusion about when the inversion is used and when not.
Took a new scurve and analyzed the data.
Note VFAT5 & 12 were masked in this test.
> Maintenance: Update CFG_CAL_DAC to Charge Conversion for v3

- fitting/fitScanData.py
Found that in some cases scurve fitting was hitting the number of max iterations and not converging on the true fit parameter values.  This was especially true when scurve mean position was at low values of charge.  This PR addresses this concern.
Additionally poisson error bars for scurves are now assigned in scurve fit process addressing [this](https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/61#issuecomment-376870516) comment of #61.
Finally additionally debugging info is now provided when `debug` is set to True.  Namely the printing of the converged values after the fitting procedure for a channel completes. 
Previously the scurve fitting procedure was failing to converge on the true fit parameters due to the initial guess never being close enough to the true value. …
> Bug Fix: initial guess for scurve mean position was range limited 

- anaUltraScurve.py
- fitting/fitScanData.py
When not supplying the `--isVFAT3` option (e.g. for v2b electronics) the y-axis range of histograms made by `anaUltraScurve.py` was incorrect (e.g. min = max and max = min).  Additionally superfluous message printing during fitting due to poor choice of parameter limits is addressed.
Couldn't analyze v2b electronics.  Annoyed by meaningless message spam.
Re-analyzed old data.
> Bug Fix:  Bad histo range and superfluous warning message printing in anaUltraScurve.py

- anaUltraScurve.py
- anautilities.py
- mapping/chamberInfo.py
Addresses: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/120
Places a given observable, in this case scurve sigma and scurve noise, in a ieta vs. strip/chan map of the detector in a single plot.  Will help people not familiar with 3x8 grid plots to visualize a given observable.
> New Feature: 2D Detector Map
